### ISSUE TITLE
Opracowanie zbierania statystyk przez agenta

### ISSUE THREAD

**Issue by jedrek18** [Esthaor/ProjektTin#4]
Pomiar ruchu (przesłanych bajtów):
- na określonym porcie/portach
- ze zwracaniem alarmów przy przekroczeniu zadanego progu

**Comment by lipin-michal** [comment]
W razie problemów z kompilacją przez cmake'a, polecam:
`g++ Agent/include/Agent.h Agent/include/Socket.h Agent/src/Agent.cpp Agent/src/Socket.cpp Agent/src/main.cpp -lboost_system -lboost_thread -lpcap`
I pozdrawiam.
